#!/usr/bin/env bash
# Regenerate modules/BgfxRenderer/Shaders/fs_light.bin.h from fs_light.sc.
#
# The build does NOT compile .sc files — editing one does nothing until its .bin.h is regenerated by
# hand. This script is that step, written down so the next person does not have to reconstruct it.
#
# The `mtl` variant is a PLACEHOLDER (no Metal backend on this toolchain) and is carried over from the
# existing header verbatim rather than recompiled.
set -euo pipefail

ROOT="C:/Users/alexi/Documents/projects/groveengine"
SHADERC="$ROOT/build/_deps/bgfx-build/cmake/bgfx/shaderc.exe"
SRC="$ROOT/modules/BgfxRenderer/Shaders"
INC="$ROOT/build/_deps/bgfx-src/bgfx/src"
TMP="$(dirname "$0")/shaderout"
mkdir -p "$TMP"

NAME="${1:-fs_light}"   # ex: tools/regen_shader.sh fs_sprite fragment
TYPE="${2:-fragment}"

compile () {   # $1 = variant suffix, $2 = platform, $3 = profile
  "$SHADERC" -f "$SRC/$NAME.sc" -o "$TMP/${NAME}_$1.bin.h" \
    --type "$TYPE" --platform "$2" -p "$3" \
    --varyingdef "$SRC/varying.def.sc" -i "$INC" \
    --bin2c "${NAME}_$1"
}

compile spv   linux   spirv
compile glsl  linux   130
compile dx11  windows s_5_0

echo "--- compiled variants ---"
wc -c "$TMP"/${NAME}_*.bin.h
